"""TypeScript type generator."""
from typing import Dict, Any, List

def infer_type(value: Any) -> str:
    if isinstance(value, bool): return 'boolean'
    if isinstance(value, int): return 'number'
    if isinstance(value, float): return 'number'
    if isinstance(value, str): return 'string'
    if isinstance(value, list): return 'any[]'
    if isinstance(value, dict): return 'Record<string, any>'
    return 'any'

def generate_types(data: Dict[str, List[Dict]]) -> str:
    lines = ['// Auto-generated by mockapi', '// Do not edit manually', '']
    for collection, items in data.items():
        if not items or not isinstance(items, list): continue
        name = collection[0].upper() + collection[1:]
        if name.endswith('s'): name = name[:-1]  # users -> User
        lines.append(f'export interface {name} {{')
        sample = items[0]
        for key, val in sample.items():
            ts_type = infer_type(val)
            lines.append(f'  {key}: {ts_type};')
        lines.append('}')  
        lines.append(f'export type {name}List = {name}[];')
        lines.append('')
    return '\n'.join(lines)
